---
- hosts: 20.37.15.213
  become: true
  tasks:

    - name: install dependencies
      apt:
        pkg: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - apt-transport-https
        - software-properties-common
        state: present 

    - name: fetch and save docker gpg file
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/docker-archive-keyring.gpg > /dev/null

    - name: initialise docker repos
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: execute repos cache update
      apt:
        update_cache: true

    - name: install docker packages
      apt:
        name: docker-ce
        state: present

    - name: run docker hello world to check whether docker is successfully installed
      shell: docker run hello-world
      register: test
    
    - debug: 
        msg: "{{ test }}"

    - name: install portainer
      shell: docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
